version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: weather_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_pipeline
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: weather_adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  pgdata:
